### PR TITLE
bug: unterminated take operator

### LINKED ISSUE #158: Circular dependency with take(1) reaches Maximum call stack size
The following code is able to reach maximum call stack size and I do not see why.

```
var value$proxy = xs.create(); 
var content$ = value$proxy.startWith(1);
var value$ = xs.of(1).map(_ => content$.take(1)).flatten();
value$proxy.imitate(value$)
content$.addListener({
    next: (x) => bin.log("content$proxy: ", x),
  complete: () => bin.log("COMPLETE"),
  error: () => bin.log("ERROR")
})
value$proxy.addListener({
  next: (x) => bin.log("Value$proxy: ", x),
  complete: () => bin.log("COMPLETE"),
  error: () => bin.log("ERROR")
})
```

See also the log of the following webpackbin: http://www.webpackbin.com/4JfBs1HQf 
(**Warning**:  It might take a while to load and you probably don't want to save anything at the risk of crashing your browser tab)

Should not the take(1) operator prevent the proxystream from reaching maximum call stack size?

I believe this construction worked in xstream 6.0.0

### PR DESCRIPTION
**Pull request by MidnightWonderer**
This fixes #158 but IMO `imitate` still not a good interface, though.  
It is very special operator distinct with other operators.

### CODE REVIEW

**Comment by staltz** [comment]
This looks correct, thanks, but I need to do some modifications to `master` branch so we use TypeScript 2.0. Will merge it soon

**Comment by staltz** [comment]
Can I ask you to rebase this with `master` so that it has only the fix to TakeOperator and the test?

**Comment by MidnightWonderer** [comment]
Done, no conflict.
I don't mind nitpicking comment.
Feel free to review the code style.

File: src/core.ts [hunk 1]
```diff
@@ -1177,9 +1177,10 @@ export class TakeOperator<T> implements Operator<T, T> {
   _n(t: T) {
     const u = this.out;
     if (u === NO) return;
-    if (this.taken++ < this.max - 1) {
+    const taken = ++this.taken;
+    if (taken < this.max) {
       u._n(t);
-    } else {
+    } else if (taken == this.max) {
```
Comment (staltz) [inline src/core.ts]: Can you use triple equals here?

**Comment by staltz** [comment]
Ok, thanks! Can I ask you also to amend the commits so that the scope is `take` and not `TakeOperator`? This will affect what is shown in the changelog.

**Comment by MidnightWonderer** [comment]
I saw massive changes there.  
So I simply do copy/paste work here.

**Comment by staltz** [comment]
Thanks @MidnightWonderer !
